# Generated by Django 5.2.4 on 2025-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(max_length=25)),
                ('address', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='project')),
            ],
        ),
    ]
