# Generated by Django 5.2.3 on 2025-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='courses_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
